// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAntZKVgHqT5cK4YfN14Prns2FUNrHgx7k',
    appId: '1:190190104151:web:ed38dd178696543b667d12',
    messagingSenderId: '190190104151',
    projectId: 'dash-14707',
    authDomain: 'dash-14707.firebaseapp.com',
    storageBucket: 'dash-14707.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBroW7fAH5t7nhv6JqEsulLoPAA2dFtXxE',
    appId: '1:190190104151:android:b6694c4d61a50a34667d12',
    messagingSenderId: '190190104151',
    projectId: 'dash-14707',
    storageBucket: 'dash-14707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKZatrWf8TYkyeFqqY8BbrqJ55x0PLJ5E',
    appId: '1:190190104151:ios:690b0574c302722c667d12',
    messagingSenderId: '190190104151',
    projectId: 'dash-14707',
    storageBucket: 'dash-14707.firebasestorage.app',
    iosBundleId: 'com.example.testRocketAlgebra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKZatrWf8TYkyeFqqY8BbrqJ55x0PLJ5E',
    appId: '1:190190104151:ios:690b0574c302722c667d12',
    messagingSenderId: '190190104151',
    projectId: 'dash-14707',
    storageBucket: 'dash-14707.firebasestorage.app',
    iosBundleId: 'com.example.testRocketAlgebra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAntZKVgHqT5cK4YfN14Prns2FUNrHgx7k',
    appId: '1:190190104151:web:48b9fba44382360e667d12',
    messagingSenderId: '190190104151',
    projectId: 'dash-14707',
    authDomain: 'dash-14707.firebaseapp.com',
    storageBucket: 'dash-14707.firebasestorage.app',
  );
}

